---
title: "Computational Musicology Portfolio"
author: "Senn Veenboer"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
source("compmus.R")

aisc2024 <- read_csv('aisc2024.csv')
corpus <- read_csv('compmus2025.csv')

```
 


Chromagrams & Cepstograms 
=================================================


Column {.tabset}
--------------------------------------------------

### Chromagram song 1

```{r}
"features/senn-v-1.json" |>                           # Change the track
  compmus_chroma(norm = "euclidean") |>                 # Change the norm
  ggplot(aes(x = time, y = pc, fill = value)) +
  geom_raster() +
  scale_y_continuous(
    breaks = 0:11,
    minor_breaks = NULL,
    labels = c(
                "C", "C#|Db", "D", "D#|Eb",
                "E", "F", "F#|Gb", "G",
                "G#|Ab", "A", "A#|Bb", "B"
              )
  ) +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = NULL, fill = NULL) +
  theme_classic()

```

### Cepstogram song 1

```{r}
"features/senn-v-1.json" |>                           # Change the track
  compmus_mfccs(norm = "euclidean") |>                  # Change the norm
  ggplot(aes(x = time, y = mfcc, fill = value)) +
  geom_raster() +
  scale_y_continuous(
    breaks = 0:12,
    minor_breaks = NULL,
  ) +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = "Coefficient Number", fill = NULL) +
  theme_classic()                                      # Change the theme?
```

### Chroma similarity song 1

```{r}
"features/senn-v-1.json" |>                           # Change the track
  compmus_chroma(norm = "manhattan") |>                 # Change the norm
  compmus_self_similarity(
    feature = pc,
    distance = "euclidean"                             # Change the distance
  ) |>
  ggplot(aes(x = xtime, y = ytime, fill = d)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = NULL, fill = NULL) +
  theme_classic()
```



### Timber similarity song 1

```{r}
"features/senn-v-1.json" |>                           # Change the track
  compmus_mfccs(norm = "manhattan") |>                  # Change the norm
  compmus_self_similarity(
    feature = mfcc,
    distance = "euclidean"                             # Change the distance
  ) |>
  ggplot(aes(x = xtime, y = ytime, fill = d)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = NULL, fill = NULL) +
  theme_classic()                                      # Change the theme?
```



Column {.tabset}
------------------------------------------------------


### Chromagram song 2

```{r}
"features/senn-v-2.json" |>                           # Change the track
  compmus_chroma(norm = "euclidean") |>                 # Change the norm
  ggplot(aes(x = time, y = pc, fill = value)) +
  geom_raster() +
  scale_y_continuous(
    breaks = 0:11,
    minor_breaks = NULL,
    labels = c(
                "C", "C#|Db", "D", "D#|Eb",
                "E", "F", "F#|Gb", "G",
                "G#|Ab", "A", "A#|Bb", "B"
              )
  ) +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = NULL, fill = NULL) +
  theme_classic()

```


### Cepstogram song 2

```{r}
"features/senn-v-2.json" |>                           # Change the track
  compmus_mfccs(norm = "euclidean") |>                  # Change the norm
  ggplot(aes(x = time, y = mfcc, fill = value)) +
  geom_raster() +
  scale_y_continuous(
    breaks = 0:12,
    minor_breaks = NULL,
  ) +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = "Coefficient Number", fill = NULL) +
  theme_classic()                                      # Change the theme?
```

### Chroma similarity song 2 euc/cos

```{r}
"features/senn-v-2.json" |>                           # Change the track
  compmus_chroma(norm = "euclidean") |>                 # Change the norm
  compmus_self_similarity(
    feature = pc,
    distance = "cosine"                             # Change the distance
  ) |>
  ggplot(aes(x = xtime, y = ytime, fill = d)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = NULL, fill = NULL) +
  theme_classic()
```


### Timber similarity song 2

```{r}
"features/senn-v-2.json" |>                           # Change the track
  compmus_mfccs(norm = "manhattan") |>                  # Change the norm
  compmus_self_similarity(
    feature = mfcc,
    distance = "euclidean"                             # Change the distance
  ) |>
  ggplot(aes(x = xtime, y = ytime, fill = d)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +               # Change the colours?
  labs(x = "Time (s)", y = NULL, fill = NULL) +
  theme_classic()                                      # Change the theme?
```

First visualisations
===========================================================

Column {data-width=500}
------------------------------------------------

### AI Contest Visualization

```{r}
aisc2024 |>                   # Start with the data
  ggplot(                     # Set up the plot.
    aes(
      x = valence,
      y = arousal,
      colour = tempo,
      label = artist
    )
  ) +
  geom_point() +              # Scatter plot.
  geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution.
  geom_text(                  # Add text labels from above.
    x = 121,
    y = 4.91,
    label = "Onda Corta - Sud America",
    size = 3,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "center",         # Align vertical centre of label with the point.
    angle = 30                # Rotate the text label
  ) +
  geom_smooth() +
  scale_colour_viridis_c() +  # Use the popular viridis colour palette.
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud..
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light()             # Use a simpler theme.
ggplotly()
```

Column
-------------------------------------

### Corpus 2025 Visualization

```{r}
corpus |>                   # Start with the data
  ggplot(                     # Set up the plot.
    aes(
      x = valence,
      y = arousal,
      colour = tempo,
      label = filename
    )
  ) +
  geom_point(aes(size = ifelse(filename %in% c("senn-v-1", "senn-v-2"), 3, 1))) +              # Scatter plot.
  geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution.
  geom_smooth() +
  scale_colour_viridis_c() +  # Use the popular viridis colour palette.
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud..
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light()             # Use a simpler theme.
ggplotly()

```